module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🧩', '🍉', '💜', '🌸', '🪴', '💊', '💫', '🍂', '🌟', '🎋', '😶‍🌫️', '🫀', '🧿', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/EuojtiL98sh8MUPvDRxv8k',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://files.catbox.moe/frwmcr.jpg',
    NEWSLETTER_JID: '120363421928318889@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: '𝗦𝗛𝗔𝗚𝗚𝗬𝗔 𝗠𝗗 𝗠𝗜𝗡𝗜',
    OWNER_NAME: 'Shaggya',
    OWNER_NUMBER: '94788262515',
    BOT_VERSION: '5.0.0',
    BOT_FOOTER: '>𝗦𝗛𝗔𝗚𝗚𝗬𝗔 𝗠𝗗 𝗠𝗜𝗡𝗜',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029Vb6nJGN3GJOp1paV4y3p',
};
